### ISSUE TITLE
Move all repeated tasks from setcronjob.com to Bull Repeated Jobs

### ISSUE THREAD

**Issue by aptro** [alexjv89/cashflowy#64]
- cost optimization: setcronjob is a paid service
- One less tool to use.
- All cronjobs will be part of the same code base.
- Easy setup for self-hosting.

**Comment by alexjv89** [comment]
@aptro - write a small report of what changes your made, in order to close the issue and the post it as a comment before closing the post. 

**In the closing commit you can mention:**
1) the challenges that you faced
2) decisions that you took
3) changes made if any

**Benefits of doing so:** 
1) It gives other contributors some sense of how engineering is done at this project (for other to learn the accepted practices)
2) It gives other contributors a sense of what fix was deployed without having to dive in to the codebase.  
3) It is a reference for yourself as much as it is for others. 

Here is an example of how it should be done - https://github.com/alexjv89/cashflowy/issues/88

**Comment by aptro** [comment]
We have added all existing crons i.e surface_crawl, weekly, monthly stat mails and UAM calculation to bull repeated job. https://github.com/OptimalBits/bull#repeated-jobs

Add a view for all the active repeat jobs. 
A Cronjob can be deactivated from the bull dashboard(```/bull```). 
<img width="1196" alt="screenshot 2019-02-18 at 11 24 57 pm" src="https://user-images.githubusercontent.com/10391409/52996462-b8d60e00-3443-11e9-8ffb-b2d7cc55e090.png">

commits: 5e2e5070007f98e7aef1d1db40eb7eb1b1b7d8c3
